apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ms-strassenverkehrsamt
  name: ms-strassenverkehrsamt
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: ms-strassenverkehrsamt
    spec:
      containers:
      - image: ms-strassenverkehrsamt-frontend
        name: ms-strassenverkehrsamt-frontend
        ports:
        - containerPort: 80
      - image: ms-strassenverkehrsamt-backend
        name: ms-strassenverkehrsamt-backend
        ports:
        - containerPort: 8080
        - containerPort: 50051
      - image: mongo
        name: ms-strassenverkehrsamt-db
        volumeMounts:
          - mountPath: /data/db
            name: db
      - image: mongo-express
        name: ms-strassenverkehrsamt-db-ui
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: "localhost"
      restartPolicy: Always
      volumes:
        - name: db
          gcePersistentDisk:
            pdName: ms-strassenverkehrsamt
            fsType: ext4
status: {}
