version: "3.8"
services:
    mongodb:
        image: mongo
        container_name: ms_strassenverkehrsamt_db
        restart: unless-stopped
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        networks:
            - backend

    mongo-express:
        image: mongo-express
        container_name: ms_strassenverkehrsamt_db_ui
        restart: unless-stopped
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_SERVER: ms_strassenverkehrsamt_db
        networks:
            - backend

    backendserver:
        build: backend/.
        container_name: ms_strassenverkehrsamt_backend
        networks:
            - backend
            - frontend

    webapp:
        build: frontend/.
        container_name: ms_strassenverkehrsamt_frontend
        networks:
            - frontend

    webproxy:
        build: webproxy/.
        container_name: ms_strassenverkehrsamt_webproxy
        ports:
            - 8080:80
        networks:
            - frontend

networks:
    backend:
    frontend:
