version: "3.8"
services:
    mongodb:
        image: mongo
        container_name: ms_strassenverkehrsamt_db
        restart: unless-stopped
        ports:
            - 27017:27017
        networks:
            - backend

    mongo-express:
        image: mongo-express
        container_name: ms_strassenverkehrsamt_db_ui
        restart: unless-stopped
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: ms_strassenverkehrsamt_db
        networks:
            - backend

    backendserver:
        build: backend/.
        container_name: ms_strassenverkehrsamt_backend
        ports:
            - 5410:8080
        networks:
            - backend
            - frontend

    webapp:
        build: frontend/.
        container_name: ms_strassenverkehrsamt_frontend
        volumes:
            - ./data/logs:/var/log/nginx
        ports:
            - 5420:80
        networks:
            - frontend

    webproxy:
        build: webproxy/.
        container_name: ms_strassenverkehrsamt_webproxy
        ports:
            - 8080:80
        networks:
            - frontend
        depends_on:
            - backendserver
            - webapp

networks:
    backend:
    frontend:
